### ISSUE TITLE
inpatient operations inconsistencies Nov 2022 -> Sept 2023

### ISSUE THREAD

**Issue by erobitschek** [dsgelab/Finregistry_detailed_longitudinal_and_endpoint_generation#11]
Our group found that the data for inpatient operations in the DL file appears suspiciously truncated in the version from September 11, 2023. For example, there are over a million rows of data corresponding to inpatient operations in 1997 but that number changes and varies and drops radically over the years in a way that doesn’t make medical sense. For instance there are 3 rows corresponding to inpatient operations _total_ in 2009. The previous DL version from November 2022 was more consistent and had hundreds of thousands of operations per year including in 2009. 

Is this data missing from the new version, or were the operations reclassified somehow?

You can see this issue if you extract the inpatient operations from the `detailed_longitudinal_2023-09-11.csv` as below. 

```bash
awk -F "," 'BEGIN{print "FINREGISTRYID,PVM,EVENT_YRMTH,EVENT_AGE,INDEX,SOURCE,ICDVER,CATEGORY,CODE1,CODE2,CODE3,CODE4,CODE5,CODE6,CODE7"} {if ($6 == "OPER_IN") {print}}' $DL_FILE_PATH > $OUT_FILE_PATH```

**Comment by erobitschek** [comment]
Thank you! Any updates on this?

**Comment by ferroteo** [comment]
the new code release is now available online [here](https://github.com/dsgelab/Finregistry_detailed_longitudinal_and_endpoint_generation/releases)
and the new DL file will be available on SD desktop by tomorrow
